# Generated by Django 6.0.2 on 2026-03-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('user__username',), 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='nickname',
        ),
    ]
