# Generated by Django 6.0.2 on 2026-03-18 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_article_number_of_views_article_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(related_name='viewed_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
