# Generated by Django 6.0.2 on 2026-03-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_article_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='info_about_author',
        ),
    ]
