# Generated by Django 6.0.2 on 2026-03-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='latest_update',
        ),
    ]
